//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ibf.Wpf.AutoConnector.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ibf.Wpf.AutoConnector.View.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///            6G2LacPH3L64Ql1E5r9MrM2qyq6nTzjE4/+
        ///            vv7MmNskeab8LJolizMzoX7AoyTN0tbve+iW9ZrL5oGDT+TjCj9c+H41+tAHqQJkga46T55YQ+UgXqSh
        ///            jfCknsta7OsKP+8XntlDOyElUvS4744BuSffL/CTL98GEb765jFnm8nvVURoZ9u5Ms3rD9Y8Wld+5Llr
        ///            PHvTl3FJVOxqYFuNbECw5lFJ1dt/2uIMbKPCrzORSACd3IC1OX9ANSJyGPaknp4388zEq6PATjLy4qvG
        ///            XhgKJ1V5I4zfEtwzX65ZNd6DOJzM5UQ6A5p5qzOdbdieBQbgF7GnHyTuT/x4iBFhVzKev6ff/eDkJ+8+
        ///            TLhHa79pLAbjcFFQNU7XEzX+n7PrZHY+svD16znJJxY4gbC+uOTR3YdcnpzRAAABAAkAAAAAA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
    }
}
